#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory


cp completed log.interIsoFoam
cp -r 0.orig 0

#------------------------------------------------------------------------------
