name: Upload Python Package

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:

  deploy:
    needs: build-wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Build distribution artifacts
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_FMU4FOAM_API_TOKEN }}
        run: |
          ls dist
          twine upload dist/*

